minors dependencies fixes
RGB-Tools/rgb-lightning-node pull request #21
Opened 2024-02-14 16:49 UTC by vincenzopalazzo

This is a minor change that require also updating the rust-lightning to compile it on my system

See commits for error description

2024-02-14 17:21 UTC, zoedberg commented
If you don't run `cargo update` this fix should not be needed because the `Cargo.lock` file is pointing to the correct dependencies. Anyway it's my fault that I've pointed rgb-lib to `master`, I should have pointed it to a dedicated branch instead.

If you want to fix my error you can update this PR changing rgb-lib branch from `master` to `rln_v0.10` and if you want to fix also the `rust-toolchain.toml` file then you can remove the `TODO` and put `stable` in place of `1.71`.

2024-02-14 17:30 UTC, vincenzopalazzo commented
Thanks! @zoedberg 

Force push the change that you suggest, and also modify the ldk version with the correct branch of rgb-lib

2024-02-15 09:48 UTC, vincenzopalazzo commented
Included the https://github.com/RGB-Tools/rust-lightning/pull/3 change :) not it is ready to review nad merge if it is all ok

2024-02-15 10:10 UTC, zoedberg requested changes
there's an unsigned commit with a wrong commit message. please squash them into a single commit called `bump rust + fix rgb-lib version`

2024-02-15 13:42 UTC, vincenzopalazzo commented
Done! Thanks for the review!

2024-02-15 14:26 UTC, zoedberg approved these changes
LGTM, thanks for your contribution :)

2024-02-15 14:26 UTC, merged